title: 数据库原理与应用
description: Principles of Database and Application
theme: just-the-docs

url: https://abotw.github.io/db

aux_links:
  Repo: https://github.com/abotw/db
  头歌: https://www.educoder.net/